import type { NextPage } from 'next'
import Head from 'next/head'
import Script from 'next/script'
import { useState } from 'react'

import styles from '../styles/Home.module.css'

declare global {
  interface Window {
    netreviewsWidget02Main: Record<string, any>
  }
}

const Home: NextPage = () => {
  const [reviews, setReviews] = useState(false)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{`${reviews}`}</h1>
      <div className="NETREVIEWS_PRODUCT_STARS" data-product-id="200098673"></div>
      <div className='NETREVIEWS_PRODUCT_REVIEWS' data-product-id="200098673" data-product-price="129.9" data-product-name="Vibranza Perfume de Mujer" data-product-url="https://esika.tiendabelcorp.com:443/pe/vibranza-perfume-de-mujer/p/200098673" data-product-img-url="https://belc-bigdata-mdm-images-prd.s3.amazonaws.com/images/FotoProductoFondoBlancoWebRedes/200098673-FotoCategoria.jpg">
      </div>
      <Script
        id="verified-reviews"
        src="https://cl.avis-verifies.com/co/cache/c/a/3/ca3219e8-e546-1024-7d18-3611de5c37fb/AWS/PRODUCT_API/tag.min.js"
        onLoad={() => setReviews(true)}
      />
    </div>
  )
}

export default Home
